steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/grpc-helloworld', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/grpc-helloworld']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'grpc-helloworld'
      - '--image=gcr.io/$PROJECT_ID/grpc-helloworld'
      - '--platform=managed'
      - '--use-http2'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=50051'

# Specify the images to store as artifacts
images:
  - 'gcr.io/$PROJECT_ID/grpc-helloworld'
